#!/bin/sh
SOURCE=$1
content=$(wpctl get-volume $SOURCE | cut -d\: -f 2 )
if [[ "$content" == *"MUTED"* ]]; then
  echo 0
  exit 0
fi

vol=$(wpctl get-volume $SOURCE | cut -d\: -f 2|cut -f2 -d\  )
echo "$vol*100"|bc
